version: "3.8"

services:
  client:
    container_name: client
    image: beerly-client
    build: 
      context: .
      target: base
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000